const industryList = [
  { value: "Accounting Firm" },
  { value: "Agriculture" },
  { value: "Advertising Agency" },
  { value: "Aerospace &amp; Defense" },
  { value: "Apparel" },
  { value: "Architecture Firm" },
  { value: "Automotive" },
  { value: "Aviation" },
  { value: "Bank" },
  { value: "Bars/Nightclubs" },
  { value: "Beauty/Cosmetics" },
  { value: "Business Consulting" },
  { value: "Cannabis" },
  { value: "Casino" },
  { value: "Computer Software" },
  { value: "Construction" },
  { value: "Country Club" },
  { value: "Doctor" },
  { value: "E-Commerce" },
  { value: "Education" },
  { value: "Electronics" },
  { value: "Employee Benefits" },
  { value: "Energy" },
  { value: "Entertainment" },
  { value: "Financial Services" },
  { value: "Fitness" },
  { value: "Food &amp; Beverage" },
  { value: "Gas Stations" },
  { value: "Healthcare" },
  { value: "Hospitals" },
  { value: "Hotel Group" },
  { value: "Industrial" },
  { value: "Insurance Broke" },
  { value: "Insurance Company" },
  { value: "Investment Firm" },
  { value: "Law Firm" },
  { value: "Maintenance" },
  { value: "Manufacturer" },
  { value: "Marketing Firm" },
  { value: "Media" },
  { value: "Medical Equipment" },
  { value: "Merchant Services" },
  { value: "Moving/Storage" },
  { value: "Municipality" },
  { value: "Non-Profit" },
  { value: "Nursing Home" },
  { value: "Office Supplies" },
  { value: "Packaging" },
  { value: "Parking Garage" },
  { value: "Payroll" },
  { value: "Pet Care" },
  { value: "Pharmaceutical" },
  { value: "Press" },
  { value: "Private Equity" },
  { value: "Property Management" },
  { value: "Public Relations" },
  { value: "Publishing" },
  { value: "Real Estate" },
  { value: "Recruiting/Staffing" },
  { value: "Religious" },
  { value: "Restaurant Group" },
  { value: "Retail" },
  { value: "Risk Management" },
  { value: "Security" },
  { value: "Spa" },
  { value: "Sports" },
  { value: "Supermarket" },
  { value: "Technology Company" },
  { value: "Telecommunications" },
  { value: "Title Insurance" },
  { value: "Transportation" },
  { value: "Union" },
  { value: "University" },
  { value: "Waste Management" },
  { value: "Wholesaler" },
];

export { industryList };
